#!/usr/bin/env bash

set -e

BACKUPDIR="$(dirname "${BASH_SOURCE[0]}")"
historyjson="$BACKUPDIR/history $(date +"%F %r").json"
studentjson="$BACKUPDIR/students $(date +"%F %r").json"

if [[ -f $historyjson ]]; then
    echo "Removing old $historyjson"
    rm "$historyjson"
fi

if [[ -f $studentjson ]]; then
    echo "Removing old $studentjson"
    rm "$studentjson"
fi

echo "Exporting $studentjson"
# if ! command -v bc &>/dev/null; then
if ! mongoexport --uri=mongodb://soda:dev@naruto:57017/soda -c students -o "$studentjson" --jsonArray --pretty; then
    echo "Error: exporting students collection failed" >&2
    exit 2
fi
echo "Exporting $historyjson"
if ! mongoexport --uri=mongodb://soda:dev@naruto:57017/soda -c history -o "$historyjson" --jsonArray --pretty; then
    echo "Error: exporting students collection failed" >&2
    exit 2
fi
exit 0
