#!/usr/bin/env bash
set -e

METEORDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
SRCDIR="/web"
bundle="${SRCDIR}/bundle"

npmrc="${bundle}/programs/server/.npmrc"
PATH="${SRCDIR}/nodejs/bin:${PATH}"
export PATH

cd "$METEORDIR" || exit 2

echo "Stopping soda"
sudo systemctl stop soda.service
if [[ -d $bundle ]]; then
    rm -rf "$bundle"
fi

if ! meteor build --directory "$SRCDIR"; then
    echo "Meteor build failed" >&2
    exit 2
fi

cd "${bundle}/programs/server" || exit 2
echo "python=/usr/bin/python2.7" >"$npmrc"
if ! npm install; then
    echo "Error: 'npm install' failed" >&2
    exit 2
fi

echo "Starting soda"
sudo systemctl start soda.service
echo "Bye!"
exit 0
